
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';
import { config, environment } from '@/config/environment';

const SUPABASE_URL = config.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = config.supabaseAnonKey;

// Explicitly set storage to ensure consistent key usage
const storageKey = config.storage.authTokenKey; // Use environment-specific storage key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  },
  global: {
    // Add retries to improve reliability
    fetch: (url, options) => {
      return fetch(url, { ...options, cache: 'no-store' });
    }
  }
});

// Log connection information in non-production environments
if (environment !== 'production') {
  console.log(`Supabase client initialized for ${environment} environment`);
  console.log(`Connected to: ${SUPABASE_URL}`);
}
